services:
  server:
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      NODE_ENV: dev

# Don't use external proxy network in dev mode
networks:
  default:
    external: false