version: '3'
services:
  db:
    build:
      context: ./db
      dockerfile: pgdb.dockerfile
    environment:
      POSTGRES_USER: dockeruser
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    # To persist the data externally, uncomment the following lines
    #volumes:
    #  - ./db/db_data:/var/lib/postgresql/data
  api:
    build:
      context: ./api
      dockerfile: api.dockerfile
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://dockeruser:${DB_PASSWORD}@db:5432/mydb
    volumes:
      - ./api:/app
      - ./web/static:/app/web/static